# Generated by Django 4.1.5 on 2023-01-18 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('matricula', models.TextField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('TURISMO', 'Turismo'), ('MOTOCICLETA', 'Motocicleta'), ('MOVILIDADREDUCIDA', 'Movilidad reducidad')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAbono',
            fields=[
                ('nombre', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('duracion', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPlaza',
            fields=[
                ('tipo', models.CharField(choices=[('TURISMO', 'Turismo'), ('MOTOCICLETA', 'Motocicleta'), ('MOVILIDADREDUCIDA', 'Movilidad reducidad')], max_length=50, primary_key=True, serialize=False)),
                ('tarifa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcentajePlazas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('numPlazas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plaza',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADA', 'Ocupada'), ('ABONOLIBRE', 'Libre con abono'), ('ABONOOCUPADA', 'Ocupada con abono')], max_length=50)),
                ('tipoPlaza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parkingapp.tipoplaza')),
            ],
        ),
        migrations.CreateModel(
            name='Abonado',
            fields=[
                ('cliente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='parkingapp.cliente')),
                ('dni', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('tarjeta', models.CharField(max_length=255)),
                ('fechaSuscripcion', models.DateTimeField()),
                ('fechaCancelacion', models.DateTimeField()),
                ('activo', models.BooleanField()),
                ('pin', models.IntegerField()),
                ('plaza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parkingapp.plaza')),
                ('tipoAbono', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parkingapp.tipoabono')),
            ],
            bases=('parkingapp.cliente',),
        ),
    ]
