# Generated by Django 4.1.5 on 2023-01-18 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocupa',
            fields=[
                ('pin', models.IntegerField(primary_key=True, serialize=False)),
                ('entrada', models.DateTimeField()),
                ('salida', models.DateTimeField()),
                ('activo', models.BooleanField()),
                ('costeTotal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parkingapp.cliente')),
                ('plaza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parkingapp.plaza')),
            ],
        ),
    ]
