# Generated by Django 4.1.5 on 2023-01-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0002_ocupa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('TU', 'Turismo'), ('MO', 'Motocicleta'), ('MR', 'Movilidad reducida')], max_length=2),
        ),
        migrations.AlterField(
            model_name='plaza',
            name='estado',
            field=models.CharField(choices=[('LI', 'Libre'), ('OC', 'Ocupada'), ('AL', 'Abono libre'), ('AO', 'Abono ocupada')], max_length=2),
        ),
        migrations.AlterField(
            model_name='tipoplaza',
            name='tipo',
            field=models.CharField(choices=[('TU', 'Turismo'), ('MO', 'Motocicleta'), ('MR', 'Movilidad reducida')], max_length=2, primary_key=True, serialize=False),
        ),
    ]
