# Generated by Django 4.1.5 on 2023-01-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0003_alter_cliente_tipo_alter_plaza_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonado',
            name='fechaSuscripcion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
