# Generated by Django 4.1.5 on 2023-01-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0004_alter_abonado_fechasuscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonado',
            name='fechaSuscripcion',
            field=models.DateTimeField(),
        ),
    ]
